---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mosquitto-config
  namespace: home-automation
data:
  mosquitto.conf: |

    persistence true
    persistence_location /mosquitto/data/
    log_dest stdout
    
    # Ref: https://moreillon.medium.com/encrypted-mosquitto-mqtt-broker-in-kubernetes-26bb7acd11c7
    # # MQTTS listener
    # listener 8883
    # protocol mqtt

    # cafile /etc/ssl/certs/ca-certificates.crt
    # keyfile /mosquitto/certs/tls.key
    # certfile /mosquitto/certs/tls.crt

    # # WS Listener
    # listener 9001
    # protocol websockets

    allow_anonymous false
    password_file /mosquitto/config/passwordfile.txt


