---
# yaml-language-server: $schema=https://kochhaus-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mosquitto-secret
  namespace: home-automation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-k3s
  target:
    name: mosquitto-secret
    template:
      data:
        passwordfile.txt: |
          {{ .MQTT_USERNAME }}:{{ .MQTT_PASSWORD }}
  dataFrom:
    - extract:
        key: mosquitto
