---
apiVersion: v1
kind: Service
metadata:
  name: mosquitto-metallb
  namespace: home-automation
  annotations:
    metallb.universe.tf/allow-shared-ip: home-automation-lb
spec:
  selector:
    app: mosquitto
  ports:
    - protocol: TCP
      port: 1883
  type: LoadBalancer
  loadBalancerIP: "${LB_HOMEAUTOMATION}"
  externalIPs: ["${LB_HOMEAUTOMATION}"]
