---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/kustomization-kustomize-v1.json

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname system-upgrade-controller
  namespace: flux-system
spec:
  interval: 30m
  timeout: 5m
  targetNamespace: tools
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  path: ./apps/tools/system-upgrade-controller/app
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      APP: *appname

---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/raw/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname system-upgrade-controller-plans
  namespace: flux-system
spec:
  targetNamespace: tools
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  dependsOn:
    - name: system-upgrade-controller
  path: ./apps/tools/system-upgrade-controller/plans
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  wait: false
  interval: 30m
  timeout: 5m
  postBuild:
    substitute:
      APP: *appname
