# Use deployment instead of helm chart because this copies an existing docker deployment. In future, we can use helm.
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: monitoring
  name: "${APP}"
  labels:
    app: "${APP}"
spec:
  replicas: 1
  strategy:
    type: Recreate  # Don't use RollingUpdate because PVC can only be mounted by one pod at a time
  selector:
    matchLabels:
      app: "${APP}"
  template:
    metadata:
      labels:
        app: "${APP}"
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:11.5.1
        env:
        - name: GF_SERVER_ROOT_URL
          value: "%(protocol)s://%(domain)s:/grafana/"
        - name: GF_SECURITY_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: grafana-admin-secret
              key: admin-user
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana-admin-secret
              key: admin-password
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_ORG_ROLE
          value: Viewer
        - name: GF_AUTH_ANONYMOUS_ORG_NAME
          value: Main Org.
        volumeMounts:
        - name: data
          mountPath: /var/lib/grafana/
        ports:
          - containerPort: 3000
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: "${PV_CLAIM}"
