---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: media
  name: tautulli
  labels:
    app: tautulli
spec:
  replicas: 1
  strategy:
    type: Recreate  # Don't use RollingUpdate because PVC can only be mounted by one pod at a time
  selector:
    matchLabels:
      app: tautulli
  template:
    metadata:
      labels:
        app: tautulli
    spec:
      containers:
      - name: tautulli
        image: linuxserver/tautulli@sha256:04d54116bc08923e337f49625c67f6d6d07ba7eaf484c88b0e5c7d1aef43fa52
        env:
        - name: TZ
          value: "${TIMEZONE}"
        livenessProbe:
          failureThreshold: 10000
          httpGet:
            path: /
            port: 8181
        volumeMounts:
        - name: config
          mountPath: /config/
        ports:
          - containerPort: 8181
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: tautulli-config
