---
apiVersion: v1
kind: Service
metadata:
  name: tautulli-metallb
  namespace: media
  annotations:
    metallb.universe.tf/allow-shared-ip: media-lb
spec:
  selector:
    app: "tautulli"
  ports:
  - name: webui
    protocol: TCP
    port: 8181
    targetPort: 8181
  type: LoadBalancer
  loadBalancerIP: "${LB_MEDIA}"
