---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - externalsecret.yaml
  - configmap-env.yaml
  - configmap-caddy.yaml
  - pvc-inventory-data.yaml
  - pvc-inventory-db.yaml
  - postgres.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
