---
# Based on https://github.com/samip5/k8s-cluster/tree/main/k8s/nebula/apps/databases/influx

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname influxdb
  namespace: flux-system
spec:
  interval: 30m
  timeout: 5m
  targetNamespace: databases
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  dependsOn:
    - name: infra-configs
  path: ./apps/databases/influxdb/app
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute:
      APP: *appname
      APP_UID: "568"
      APP_GID: "568"
      PV_CLAIM: influx-v1-data
      PV_CAPACITY: 50Gi
      PV_STORAGECLASS: longhorn-diskencrypt-global
    substituteFrom:
      - kind: ConfigMap
        name: global-config
      - kind: Secret
        name: global-secrets
      - kind: ConfigMap
        name: cluster-config
      - kind: Secret
        name: cluster-secrets
  patches:
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
        kind: Kustomization
        metadata:
          name: not-used
          namespace: not-used
        spec:
          decryption:
            provider: sops
            secretRef:
              name: sops-age
          postBuild:
            substitute: {}
            substituteFrom:
              - kind: ConfigMap
                name: global-config
              - kind: Secret
                name: global-secrets
              - kind: ConfigMap
                name: cluster-config
              - kind: Secret
                name: cluster-secrets
      target:
        kind: Kustomization
        group: kustomize.toolkit.fluxcd.io
        version: v1beta2
