---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: inf-dazzathewiz-com
  namespace: cert-manager
spec:
  secretName: inf-dazzathewiz-com-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.inf.dazzathewiz.com"
  dnsNames:
  - "inf.dazzathewiz.com"
  - "*.inf.dazzathewiz.com"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "traefik,rancher"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: ""
