---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: inf-personal-domain
  namespace: cert-manager
spec:
  secretName: inf-personal-domain-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.inf.${PERSONAL_DOMAIN}"
  dnsNames:
  - "inf.${PERSONAL_DOMAIN}"
  - "*.inf.${PERSONAL_DOMAIN}"
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "traefik,cattle-system,longhorn-system,databases"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-namespaces: ""
