---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: influxdb-user-secret
  namespace: databases
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-k3s
  target:
    creationPolicy: Owner
  data:
  - secretKey: influxdb-user
    remoteRef:
      key: influxdb-user
      property: username
  - secretKey: influxdb-password
    remoteRef:
      key: influxdb-user
      property: password
