---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: influxdb-v2-user-secret
  namespace: databases
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-k3s
  target:
    creationPolicy: Owner
  data:
  - secretKey: admin-token
    remoteRef:
      key: influxdbv2
      property: token
  - secretKey: admin-password
    remoteRef:
      key: influxdbv2
      property: password
