---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "${PV_CLAIM}"
  namespace: databases
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "${PV_STORAGECLASS}"
  resources:
    requests:
      storage: "${PV_CAPACITY}"
