---
apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: ceph-pve-external
  namespace: rook-ceph-external
spec:
  external:
    enable: true
  dataDirHostPath: /var/lib/rook
  cephVersion:
    image: quay.io/ceph/ceph:v16.2.11
  crashCollector:
    disable: true
  healthCheck:
    daemonHealth:
      mon:
        disabled: false
        interval: 45s
  monitoring:
    enabled: true
    externalMgrEndpoints:
      - ip: "10.10.10.34"
      - ip: "10.10.10.35"
      - ip: "10.10.10.36"
    externalMgrPrometheusPort: 9283
