---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rook-ceph-mon
  namespace: rook-ceph-external
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-k3s
  target:
    creationPolicy: Owner
    template:
      type: kubernetes.io/rook
  data:
  - secretKey: admin-secret
    remoteRef:
      key: rook-ceph-mon
      property: admin-secret
  - secretKey: ceph-secret
    remoteRef:
      key: rook-ceph-mon
      property: ceph-secret
  - secretKey: ceph-username
    remoteRef:
      key: rook-ceph-mon
      property: ceph-username
  - secretKey: cluster-name
    remoteRef:
      key: rook-ceph-mon
      property: cluster-name
  - secretKey: fsid
    remoteRef:
      key: rook-ceph-mon
      property: fsid
  - secretKey: mon-secret
    remoteRef:
      key: rook-ceph-mon
      property: mon-secret
---
apiVersion: v1
data:
  data: prox1=10.10.10.34:6789
  mapping: '{}'
  maxMonId: "2"
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: rook-ceph-mon-endpoints
  namespace: rook-ceph-external
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rook-csi-rbd-node
  namespace: rook-ceph-external
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-k3s
  target:
    creationPolicy: Owner
    template:
      type: kubernetes.io/rook
  data:
  - secretKey: userID
    remoteRef:
      key: rook-csi-rbd-node
      property: userID
  - secretKey: userKey
    remoteRef:
      key: rook-csi-rbd-node
      property: userKey
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rook-csi-rbd-provisioner
  namespace: rook-ceph-external
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-k3s
  target:
    creationPolicy: Owner
    template:
      type: kubernetes.io/rook
  data:
  - secretKey: userID
    remoteRef:
      key: rook-csi-rbd-provisioner
      property: userID
  - secretKey: userKey
    remoteRef:
      key: rook-csi-rbd-provisioner
      property: userKey
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rook-csi-cephfs-node
  namespace: rook-ceph-external
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-k3s
  target:
    creationPolicy: Owner
    template:
      type: kubernetes.io/rook
  data:
  - secretKey: adminID
    remoteRef:
      key: rook-csi-cephfs-node
      property: adminID
  - secretKey: adminKey
    remoteRef:
      key: rook-csi-cephfs-node
      property: adminKey
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: rook-csi-cephfs-provisioner
  namespace: rook-ceph-external
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-k3s
  target:
    creationPolicy: Owner
    template:
      type: kubernetes.io/rook
  data:
  - secretKey: adminID
    remoteRef:
      key: rook-csi-cephfs-provisioner
      property: adminID
  - secretKey: adminKey
    remoteRef:
      key: rook-csi-cephfs-provisioner
      property: adminKey
