---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unifi-controller-config
  namespace: infrastructure
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-diskencrypt-global
  persistentVolumeReclaimPolicy: Retain
  resources:
    requests:
      storage: 30Gi
