---
apiVersion: v1
kind: Service
metadata:
  name: unifi-controller-metallb
  namespace: infrastructure
  annotations:
    metallb.universe.tf/allow-shared-ip: infrastructure-lb
spec:
  selector:
    app: unifi-controller
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
    - protocol: UDP
      port: 3478
      targetPort: 3478
    - protocol: TCP
      port: 8443
      targetPort: 8443
  type: LoadBalancer
  loadBalancerIP: "${LB_INFRASTRUCTURE}"
