apiVersion: v1
kind: Secret
metadata:
    namespace: flux-system
    name: cluster-secrets
type: Opaque
stringData:
    LONGHORN_S3_BUCKET_NAME: ENC[AES256_GCM,data:CbpmGWOzvpe4rA==,iv:Zj4qr5vgBx6jCCAgfP6WuWGPzRPYRLjH2izsmaKcXr8=,tag:vV3E+OCZHW7xfPFrE+O3UQ==,type:str]
    LONGHORN_S3_BUCKET_REGION: ENC[AES256_GCM,data:iwSkSeyBxRdcCg==,iv:M0IkngnflEg0QNoGJYexpFrUEJR6fUkAY9oYJUjvE+c=,tag:xd1TEdOn6AGiWWWWxZ4euA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1fpgw9c2wl8e95x7zsww589e4w4wknegur5x2vhh9kasd0pcj8f4sjs2ed0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRQjc5V01lV2VtSWZXQ0RK
            czNVNUVoN1hkdVhRR3hTYXg5bktJU1FGSlN3CjYvdU8zTHFscmkvZWpSdHJOSFMr
            dHBjTlh6a2lCRUFrYy9IcWNpd3RwM1EKLS0tIFhJWHJWN2VBZjVpeXVQZE53VlIr
            NTNFTnFEV01vQmZ6Wmt3YmIveFFYSjAKxbvGrmYhA5z9ZyifWnuQjqrUHl+HD4ur
            B0kt6V+ATFxzniKKVSsoW85edf/T1aHm8/aXuG1EtayglFuBIsjQIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-06-17T06:18:24Z"
    mac: ENC[AES256_GCM,data:hY7NlSZjA2NeaTqLIivafL71KuBC5VSRQhn1UGJDk6QqmED0q2OfJOBw9ljsr017MR09Wa2t4kMo7EtD554AclULkGgJOZeB9tWHslmamhmusSSn22RJohQp3t6dZS4cOzmYKTKVOPcZ0UgYuiJ5A7GysjpKm2XxfmE2dWeaRuU=,iv:UR3GTTPBmn8jLe5Xptpba0Gv0YAL7hvPLhMFIjf1Pkk=,tag:R1jdgGoNh6VLBZ1Hz3Me6Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
