---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: 1password
  namespace: flux-system
spec:
  interval: 30m
  url: url: https://1password.github.io/connect-helm-charts/
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: 1password
  namespace: flux-system
spec:
  interval: 5m
  releaseName: 1password-connect
  targetNamespace: 1password
  install:
    createNamespace: true
  chart:
    spec:
      chart: connect
      version: '1.*'
      sourceRef:
        kind: HelmRepository
        name: 1password
        namespace: flux-system
      interval: 1m
  timeout: 5m
  # Note that op-credentials secret is expected to be already configured in kubernetes
  #values:
    # See: https://github.com/1Password/connect-helm-charts/blob/main/charts/connect/values.yaml
