---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: ceph-csi
  namespace: flux-system
spec:
  interval: 30m
  url: https://ceph.github.io/csi-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ceph-csi-cephfs
  namespace: flux-system
spec:
  interval: 5m
  releaseName: ceph-csi-cephfs
  targetNamespace: ceph-csi-cephfs
  install:
    createNamespace: true
  chart:
    spec:
      chart: ceph-csi-cephfs
      version: '>=3.8.0'
      sourceRef:
        kind: HelmRepository
        name: ceph-csi
        namespace: flux-system
      interval: 1m
  timeout: 5m
