---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: emberstack
  namespace: flux-system
spec:
  interval: 30m
  url: https://emberstack.github.io/helm-charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: reflector
  namespace: flux-system
spec:
  interval: 5m
  releaseName: reflector
  targetNamespace: reflector
  install:
    createNamespace: true
  chart:
    spec:
      chart: reflector
      version: '>=7.0.0 <8.0.0'
      sourceRef:
        kind: HelmRepository
        name: emberstack
        namespace: flux-system
      interval: 1m
  timeout: 5m
