---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 30m
  url: https://charts.longhorn.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: flux-system
spec:
  interval: 5m
  releaseName: longhorn
  targetNamespace: longhorn-system
  install:
    createNamespace: true
  chart:
    spec:
      chart: longhorn
      version: '1.4.2'
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 1m
  timeout: 15m
  values:
    defaultSettings:
      backupTarget: s3://${LONGHORN_S3_BUCKET_NAME}@${LONGHORN_S3_BUCKET_REGION}/
      backupTargetCredentialSecret: longhorn-s3bucket-secret
      createDefaultDiskLabeledNodes: true
      defaultDataPath: /mnt/nvme0/
