---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 30m
  url: https://helm.traefik.io/traefik
---
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: traefik-helm-chart-value-overrides
  namespace: flux-system
data:
  values.yaml: |-
    globalArguments:
    - "--global.sendanonymoususage=false"
    - "--global.checknewversion=false"

    additionalArguments:
      - "--serversTransport.insecureSkipVerify=true"
      - "--log.level=INFO"
    
    deployment:
      enabled: true
      replicas: 3
      annotations: {}
      podAnnotations: {}
      additionalContainers: []
      initContainers: []

    ports:
      web:
        redirectTo: websecure
      websecure:
        tls:
          enabled: true
          
    ingressRoute:
      dashboard:
        enabled: false

    providers:
      kubernetesCRD:
        enabled: true
        ingressClass: traefik-external
        allowExternalNameServices: true
      kubernetesIngress:
        enabled: true
        allowExternalNameServices: true
        publishedService:
          enabled: false

    rbac:
      enabled: true

    service:
      enabled: true
      type: LoadBalancer
      annotations: {}
      labels: {}
      spec:
        loadBalancerIP: ${LB_TRAEFIK} # this should be an IP in the MetalLB range
      loadBalancerSourceRanges: []
      externalIPs: []
    
    topologySpreadConstraints:
    # # This example topologySpreadConstraints forces the scheduler to put traefik pods
    # # on nodes where no other traefik pods are scheduled.
      - labelSelector:
          matchLabels:
            app: '{{ template "traefik.name" . }}'
        maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 5m
  releaseName: traefik
  targetNamespace: traefik
  install:
    createNamespace: true
  chart:
    spec:
      chart: traefik
      version: '>=22.1.0 <24.0.0'
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 1m
  timeout: 5m
  valuesFrom:
  - kind: ConfigMap
    name: traefik-helm-chart-value-overrides
    valuesKey: values.yaml # This is the default, but best to be explicit for clarity
