---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nut-secret
  namespace: home-automation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-k3s
  target:
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: NUT
      property: username
  - secretKey: password
    remoteRef:
      key: NUT
      property: password
