---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: onepassword-k3s
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets
    - name: 1password-connect
  provider:
    onepassword:
      connectHost: https://onepassword-connect
      vaults:
        k3s: 1  # search order
      auth:
        secretRef:
        connectTokenSecretRef:
          name: onepassword-connect-token
          key: token
