---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 5m
  releaseName: external-secrets
  targetNamespace: external-secrets
  install:
    createNamespace: true
  chart:
    spec:
      chart: external-secrets
      version: '0.*'
      sourceRef:
        kind: HelmRepository
        name: 1passwoexternal-secretsrd
        namespace: flux-system
      interval: 1m
  timeout: 5m
