---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: intel-device-plugins-gpu
  namespace: flux-system
spec:
  interval: 5m
  releaseName: intel-device-plugins-gpu
  targetNamespace: intel-device
  install:
    createNamespace: true
  chart:
    spec:
      chart: intel-device-plugins-gpu
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: flux-system
      interval: 1m
  timeout: 5m
  values:
    nodeFeatureRule: true
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: intel-device-plugins-operator
  namespace: flux-system
spec:
  interval: 5m
  releaseName: intel-device-plugins-operator
  targetNamespace: intel-device
  install:
    createNamespace: true
  chart:
    spec:
      chart: intel-device-plugins-operator
      sourceRef:
        kind: HelmRepository
        name: intel
        namespace: flux-system
      interval: 1m
  timeout: 5m
