---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: longhorn-dashboard-auth
  namespace: longhorn-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-k3s
  target:
    creationPolicy: Owner
  data:
  - secretKey: users
    remoteRef:
      key: longhorn-dashboard
      property: users
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: longhorn-dashboard-basicauth
  namespace: longhorn-system
spec:
  basicAuth:
    secret: longhorn-dashboard-auth
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: svc-longhorn-headers
  namespace: longhorn-system
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: cors-allow-all
  namespace: longhorn-system
spec:
  headers:
    accessControlAllowCredentials: true
    accessControlAllowMethods:
      - "*"
    accessControlAllowOriginList:
      - "*"
    accessControlMaxAge: 100
    addVaryHeader: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: longhorn-dashboard
  namespace: longhorn-system
  annotations: 
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`longhorn.inf.dazzathewiz.com`)
      kind: Rule
      middlewares:
        - name: cors-allow-all
          namespace: longhorn-system
        - name: longhorn-dashboard-basicauth
          namespace: longhorn-system
        - name: svc-longhorn-headers
          namespace: longhorn-system
      services:
        - name: longhorn-frontend
          port: 80
          namespace: longhorn-system
  tls:
    secretName: inf-dazzathewiz-com-tls
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: linode-k3s-backup-bucket-secret
  namespace: longhorn-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-k3s
  target:
    creationPolicy: Owner
  data:
  - secretKey: AWS_ENDPOINTS
    remoteRef:
      key: linode-k3s-bucket
      property: AWS_ENDPOINTS
  - secretKey: AWS_ACCESS_KEY_ID
    remoteRef:
      key: linode-k3s-bucket
      property: AWS_ACCESS_KEY_ID
  - secretKey: AWS_SECRET_ACCESS_KEY
    remoteRef:
      key: linode-k3s-bucket
      property: AWS_SECRET_ACCESS_KEY
---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: 12-hour-snapshots
  namespace: longhorn-system
spec:
  cron: "0 */12 * * *"
  task: "snapshot"
  groups:
  - default
  retain: 4
  concurrency: 2
  labels:
    job: 12-hour-snapshots
---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: daily-backups
  namespace: longhorn-system
spec:
  cron: "0 11 * * *"
  task: "backup"
  groups:
  - default
  retain: 3
  concurrency: 2
  labels:
    job: daily-backups
---
apiVersion: longhorn.io/v1beta1
kind: RecurringJob
metadata:
  name: weekly-backups
  namespace: longhorn-system
spec:
  cron: "20 23 * * 2"
  task: "backup"
  groups:
  - default
  retain: 2
  concurrency: 2
  labels:
    job: weekly-backups
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: longhorn-disk-encrypt
  namespace: longhorn-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-k3s
  target:
    creationPolicy: Owner
  data:
  - secretKey: CRYPTO_KEY_VALUE
    remoteRef:
      key: longhorn-diskencrypt
      property: CRYPTO_KEY_VALUE
  - secretKey: CRYPTO_KEY_PROVIDER
    remoteRef:
      key: longhorn-diskencrypt
      property: CRYPTO_KEY_PROVIDER
  - secretKey: CRYPTO_KEY_CIPHER
    remoteRef:
      key: longhorn-diskencrypt
      property: CRYPTO_KEY_CIPHER
  - secretKey: CRYPTO_KEY_HASH
    remoteRef:
      key: longhorn-diskencrypt
      property: CRYPTO_KEY_HASH
  - secretKey: CRYPTO_KEY_SIZE
    remoteRef:
      key: longhorn-diskencrypt
      property: CRYPTO_KEY_SIZE
  - secretKey: CRYPTO_PBKDF
    remoteRef:
      key: longhorn-diskencrypt
      property: CRYPTO_PBKDF
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-diskencrypt-global
  storageclass.kubernetes.io/is-default-class: "true"
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  encrypted: "true"
  csi.storage.k8s.io/provisioner-secret-name: "longhorn-disk-encrypt"
  csi.storage.k8s.io/provisioner-secret-namespace: "longhorn-system"
  csi.storage.k8s.io/node-publish-secret-name: "longhorn-disk-encrypt"
  csi.storage.k8s.io/node-publish-secret-namespace: "longhorn-system"
  csi.storage.k8s.io/node-stage-secret-name: "longhorn-disk-encrypt"
  csi.storage.k8s.io/node-stage-secret-namespace: "longhorn-system"
