---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rancher
  namespace: flux-system
spec:
  interval: 5m
  releaseName: rancher-stable
  targetNamespace: cattle-system
  install:
    createNamespace: true
  chart:
    spec:
      chart: rancher
      version: '>=2.7.0 <2.8.0'
      sourceRef:
        kind: HelmRepository
        name: rancher-stable
        namespace: flux-system
      interval: 1m
  timeout: 5m
  values:
    hostname: rancher.inf.${PERSONAL_DOMAIN}
    ingress:
      tls:
        source: secret
        secretName: inf-personal-domain-tls
