---
apiVersion: v1
kind: Service
metadata:
  name: uisp-metallb
  namespace: infrastructure
  annotations:
    metallb.universe.tf/allow-shared-ip: infrastructure-lb
spec:
  selector:
    app: ubiquiti-uisp
  ports:
    - name: web-http
      protocol: TCP
      port: 6080
      targetPort: 80
    - name: web-https
      protocol: TCP
      port: 6443
      targetPort: 443
  type: LoadBalancer
  loadBalancerIP: "${LB_INFRASTRUCTURE}"
