---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: fluxcd-slackurl
  namespace: flux-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-k3s
  target:
    creationPolicy: Owner
  data:
  - secretKey: address
    remoteRef:
      key: fluxcd-slackalerts
      property: address
