---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: infra-configs
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: global-config
      - kind: Secret
        name: global-secrets
      - kind: ConfigMap
        name: cluster-config
      - kind: Secret
        name: cluster-secrets
  prune: true
  wait: true
  timeout: 5m0s
