---
# Based on https://github.com/samip5/k8s-cluster/tree/main/k8s/nebula/apps/databases/influx

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &appname portainer
  namespace: flux-system
spec:
  interval: 30m
  timeout: 5m
  targetNamespace: infrastructure
  commonMetadata:
    labels:
      app.kubernetes.io/name: *appname
  dependsOn:
    - name: infra-configs
  path: ./apps/infrastructure/portainer/app
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: flux-system
  postBuild:
    substitute:
      APP: *appname
      PV_CLAIM: portainer-data
      PV_CAPACITY: 1Gi
      PV_STORAGECLASS: longhorn-diskencrypt-global
