---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: portainer
  namespace: infrastructure
spec:
  interval: 15m
  chart:
    spec:
      chart: portainer
      version: '>=1.0.59'
      sourceRef:
        kind: HelmRepository
        name: portainer-charts
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    timeout: 10m
    remediation:
      retries: 3
  upgrade:
    timeout: 10m
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:

    service:
      type: ClusterIP

    # ingress: managed separately
          
    persistence:
      enabled: true
      existingClaim: "${PV_CLAIM}"
      storageClass: "${PV_STORAGECLASS}"
      size: "${PV_CAPACITY}"
