---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cephfs-plexdata
  namespace: rook-ceph
spec:
  storageClassName: cephfs-plexdata
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  #volumeMode: Filesystem