---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: home-automation
  name: solar-iot
  labels:
    app: solar-iot
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: solar-iot
  template:
    metadata:
      labels:
        app: solar-iot
    spec:
      containers:
      - name: solariot
        image: dazzathewiz/solariot
        volumeMounts:
        - name: config
          mountPath: /config/
      volumes:
      - name: config
        secret:
          secretName: solariot-config
