---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mosquitto-login-secret
  namespace: home-automation
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-k3s
  target:
    creationPolicy: Owner
  data:
  - secretKey: username
    remoteRef:
      key: mosquitto
      property: username
  - secretKey: password
    remoteRef:
      key: mosquitto
      property: password
