---
apiVersion: v1
kind: ConfigMap
metadata:
  name: global-config
  namespace: flux-system
data:
  TEST: test

  UNRAID_IP: 192.68.10.10
  PVE_CEPH_NFS_IP: 10.10.2.200
  MEDIA_SERVER: 10.10.2.200   # NFS server that media config connects to
