---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: media-namespace
  namespace: flux-system
spec:
  interval: 5m
  path: "./manifests/media"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  decryption:
    provider: sops
    secretRef:
      name: sops-age
  postBuild:
    substitute: {}
    substituteFrom:
      - kind: ConfigMap
        name: global-config
      - kind: Secret
        name: global-secrets
      - kind: ConfigMap
        name: cluster-config
      - kind: Secret
        name: cluster-secrets
  patches:
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
        kind: Kustomization
        metadata:
          name: not-used
          namespace: not-used
        spec:
          decryption:
            provider: sops
            secretRef:
              name: sops-age
          postBuild:
            substitute: {}
            substituteFrom:
              - kind: ConfigMap
                name: global-config
              - kind: Secret
                name: global-secrets
              - kind: ConfigMap
                name: cluster-config
              - kind: Secret
                name: cluster-secrets
      target:
        kind: Kustomization
        group: kustomize.toolkit.fluxcd.io
        version: v1beta2
