---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: changedetection-data
  namespace: tools
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-diskencrypt-global
  persistentVolumeReclaimPolicy: Retain
  resources:
    requests:
      storage: 5Gi
