---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: onepassword-k3s
  namespace: 1password
spec:
  provider:
    onepassword:
      connectHost: https://onepassword-connect.1password.svc.cluster.local:8080
      vaults:
        k3s: 1  # search order
      auth:
        secretRef:
          connectTokenSecretRef:
            name: onepassword-connect-token
            key: token
