---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: media-pv
  namespace: flux-system
spec:
  interval: 5m
  path: "./pv/media"
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
